# Promotes a new build to the Nightly channel on a schedule.

name: Promote Nightly Channel

on: push

jobs:
  promote-nightly:
    uses: danielrozenberg/cdn-configuration-not-a-fork/.github/workflows/promote-reusable-workflow.yml@main
    with:
      channel-name: 'Nightly'
      ts-file: 'promote-nightly.ts'
      amp-version: 2112231523000
