# Reusable workflow for promote jobs.

on:
  workflow_call:
    inputs:
      channel-name:
        description: 'Human readable name of the channel to promote'
        required: true
        type: string
      ts-file:
        description: 'TypeScript file to execute (with .ts), under scripts/'
        required: true
        type: string
      amp-version:
        description: 'Optional AMP version number (13 digits) to pass. Not all promotion require this, some will default to promoting based on the current version of other channels.'
        required: false
        default: ''
        type: string
