# Promotes a new build to the Nightly channel on a schedule.

name: Promote Nightly Channel

on: push

jobs:
  promote:
    if: github.repository == 'danielrozenberg/cdn-configuration-not-a-fork'
    name: Promote Nightly Channel
    runs-on: ubuntu-latest
    environment: ampprojectbot

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: ⭐ Promote Nightly Channel ⭐
        run: npx ts-node scripts/promote-nightly.ts --amp_version=2112231523000
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
